# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sctyner.github.io/
baseurl: /home/
title: Samantha Tyner
author: Samantha Tyner
description: Personal website, blog, and curriculum vitae.
avatar: profile.png
email: sctyner@iastate.edu  
github: sctyner # username
twitter: sctyner
linkedin: sctyner
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: 
  - [vendor]
  - Gemfile
  - Gemfile.lock

